<!doctype html>
<html>
<head>
<title><%= name %></title>
<link rel="stylesheet" href="/dist/{{batch}}/{{name}}/css/styles.css">
<script src="/dist/{{batch}}/{{name}}/js/source.js"></script>
</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg"
xmlns:xlink="http://www.w3.org/1999/xlink"
width="240" height="320"
viewBox="0 0 240 320 "
version="1.1">
<title>{{name}}</title>


<rect class="rect1" x="0" y="0"  width="200" height="100"  fill-rule="evenodd"/>

</svg>

</body>
</html>
